osx_image: xcode11.3
language: objective-c
branches:
  only:
    - develop
    - test
notifications:
  email: false
script:
- fastlane ios justscan
#./scripts/run-tests.sh
after-success: 
- fastlane ios test2
deploy:
  skip_cleanup: true
