# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Myv best lane <333"
  lane :bonjour do
    #print increment_version_number  incremente la version apres > fastlane > choose 1 > OK 
    #print increment_version_number(bump_type:"major") 
    #scan test unitaire sur tout le code
  end
end
